language : node_js

node_js:
  - 10.14.2

install:
- yarn

script:
- yarn build-bundle

deploy:
  provider: npm
  email: javpeiwen2010@gmail.com
  api_key: "$npm_token"
  skip_cleanup: true
  on:
    tags: true
    branch: master
  tag: latest
  condition: '$TRAVIS_TAG =~ ^v[0-9]+.[0-9]+.[0-9]+$'